// Manual, admin-triggered, one-time-but-safe-to-rerun import of conversation history that already
// exists on the RSPetStop GMA Facebook Page from BEFORE supabase/functions/facebook-messenger-
// webhook existed, or from real customers who aren't added as a Tester while pages_messaging is
// still in Meta App Review (while in Development Mode, that webhook only fires for people with a
// role on the app - see that function's own header comment). This function instead reads the
// Page's conversation history directly via Facebook's Conversations Graph API
// (GET /me/conversations) and backfills it into the SAME ChatbotConversations/ChatbotMessages
// tables the live webhook writes to - so docs/gma-conversations.html shows both without any UI
// changes.
//
// Requires FACEBOOK_PAGE_ACCESS_TOKEN to actually have read access to the Page's conversation
// history - Meta restricts how much of this it hands over even once pages_messaging is approved
// with Advanced Access, so results here are best-effort.
//
// Also requires a FACEBOOK_PAGE_ID secret (set once via `supabase secrets set FACEBOOK_PAGE_ID=...
// --project-ref hymcmesqgpliyyeghpgq`) - deliberately NOT looked up via GET /me, which turns out to
// require the pages_read_engagement permission (confirmed by a live 403 while testing this
// function); avoiding that call means this feature doesn't need to request a permission with no
// other use in this app. Each thread is also capped at
// MESSAGES_PER_CONVERSATION (Facebook's own field-expansion limit per call) and the whole run is
// capped at MAX_CONVERSATION_PAGES so one invocation can't run away - re-run this function again
// later to pick up anything Facebook's pagination didn't reach this time (safe: every message is
// deduped, see below).
//
// Dedup: every imported message is upserted on ChatbotMessages."FacebookMessageId" (the same
// unique index the live webhook already relies on for its own redelivery dedup), so re-running
// this - or overlapping with messages the live webhook has already captured - never creates
// duplicates.
//
// Page-sent messages are recorded with Role 'staff', not 'assistant' - these predate the bot, so
// they were manually typed by a person in Meta Business Suite's native inbox, not generated by
// Claude. SentByUsername is left null since Facebook's API doesn't expose which individual staff
// member sent a given message.
//
// Vision-based payment-screenshot detection (facebook-messenger-webhook's extractPaymentDetails)
// is deliberately skipped here - this is a bulk historical import, and running that over every old
// photo would be a large, mostly-unnecessary Claude API cost spike for messages nobody is waiting
// on a reply to. Photos are still downloaded and stored privately so they display inline either way.
//
// Admin-gated: the caller passes admin_username/admin_password, re-verified via
// is_admin_authorized() on every call (see supabase_chatbot_conversations_backfill.sql, which
// grants anon execute on that existing function) - same trust model as every other admin_*-gated
// feature in this codebase, no stored session.
//
// Deploy: supabase functions deploy facebook-conversations-backfill --project-ref hymcmesqgpliyyeghpgq

import { createClient } from 'npm:@supabase/supabase-js@2';

const DEFAULT_GRAPH_VERSION = 'v21.0';
const CONVERSATIONS_PER_PAGE = 25;
const MESSAGES_PER_CONVERSATION = 100;
const MAX_CONVERSATION_PAGES = 40;

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS'
};

function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), { status, headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' } });
}

interface GraphMessage {
  id?: string;
  message?: string;
  created_time?: string;
  from?: { id?: string; name?: string };
  attachments?: { data?: Array<{ image_data?: { url?: string }; mime_type?: string }> };
}

interface GraphConversation {
  participants?: { data?: Array<{ id?: string; name?: string }> };
  messages?: { data?: GraphMessage[] };
}

async function downloadAndStoreImage(
  supabase: ReturnType<typeof createClient>,
  psid: string,
  sourceUrl: string
): Promise<{ path: string; signedUrl: string } | null> {
  try {
    const res = await fetch(sourceUrl);
    if (!res.ok) return null;
    const contentType = res.headers.get('content-type') || 'image/jpeg';
    const ext = contentType.includes('png') ? 'png' : contentType.includes('webp') ? 'webp' : contentType.includes('gif') ? 'gif' : 'jpg';
    const bytes = new Uint8Array(await res.arrayBuffer());
    // "backfill-" prefix + a random suffix (rather than just Date.now(), like the live webhook
    // uses) since this loop can process many messages fast enough to collide on the millisecond.
    const path = `${psid}/backfill-${Date.now()}-${Math.random().toString(36).slice(2, 8)}.${ext}`;

    const { error: uploadError } = await supabase.storage.from('chatbot-attachments').upload(path, bytes, { contentType, upsert: false });
    if (uploadError) return null;

    const { data: signedData, error: signError } = await supabase.storage.from('chatbot-attachments').createSignedUrl(path, 60 * 60 * 24 * 60);
    if (signError || !signedData?.signedUrl) return null;

    return { path, signedUrl: signedData.signedUrl };
  } catch {
    return null;
  }
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: CORS_HEADERS });
  if (req.method !== 'POST') return jsonResponse({ error: 'Use POST.' }, 405);

  const supabaseUrl = Deno.env.get('SUPABASE_URL');
  const serviceRoleKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
  const anonKey = Deno.env.get('SUPABASE_ANON_KEY');
  const pageAccessToken = Deno.env.get('FACEBOOK_PAGE_ACCESS_TOKEN');
  const pageId = Deno.env.get('FACEBOOK_PAGE_ID');
  const graphVersion = Deno.env.get('FACEBOOK_GRAPH_API_VERSION') || DEFAULT_GRAPH_VERSION;

  if (!supabaseUrl || !serviceRoleKey || !anonKey || !pageAccessToken || !pageId) {
    return jsonResponse({
      error: !pageId
        ? "Missing the FACEBOOK_PAGE_ID secret. Find your Page's numeric ID (Page Settings > About, or Meta Business Suite > Page Settings > General) and set it with: supabase secrets set FACEBOOK_PAGE_ID=<id> --project-ref hymcmesqgpliyyeghpgq"
        : 'facebook-conversations-backfill is missing one or more required secrets.'
    }, 500);
  }

  let adminUsername: string;
  let adminPassword: string;
  try {
    const body = await req.json();
    adminUsername = String(body.admin_username ?? '');
    adminPassword = String(body.admin_password ?? '');
    if (!adminUsername || !adminPassword) throw new Error('missing field');
  } catch {
    return jsonResponse({ error: 'Body must be JSON: { admin_username, admin_password }.' }, 400);
  }

  const anonClient = createClient(supabaseUrl, anonKey);
  const { data: isAuthorized, error: authError } = await anonClient.rpc('is_admin_authorized', {
    p_username: adminUsername,
    p_password: adminPassword
  });
  if (authError || !isAuthorized) {
    return jsonResponse({ error: 'Not authorized.' }, 403);
  }

  const supabase = createClient(supabaseUrl, serviceRoleKey);

  try {
    let conversationsSeen = 0;
    let conversationsUpserted = 0;
    let messagesProcessed = 0;
    let imagesStored = 0;
    let pagesFetched = 0;
    // Conversations where Facebook confirmed the thread exists (it showed up in /me/conversations,
    // with participants) but handed back zero messages - the strongest available signal that Meta
    // is withholding message CONTENT for that customer (typically because they aren't a Tester/
    // Admin on the app while pages_messaging is still in Development Mode/Standard Access), rather
    // than the conversation genuinely being empty. Surfaced in the response so this doesn't have to
    // be guessed at from staff reports of "the conversation synced but has no messages".
    let conversationsWithNoMessages = 0;

    const fields = 'participants,messages.limit(' + MESSAGES_PER_CONVERSATION + '){message,from,created_time,attachments{data{image_data,mime_type}}}';
    let url: string | null =
      `https://graph.facebook.com/${graphVersion}/me/conversations?fields=${encodeURIComponent(fields)}&limit=${CONVERSATIONS_PER_PAGE}&access_token=${pageAccessToken}`;

    while (url && pagesFetched < MAX_CONVERSATION_PAGES) {
      pagesFetched++;
      const res = await fetch(url);
      if (!res.ok) {
        console.error('Conversations Graph API call failed:', await res.text());
        break;
      }
      const page = await res.json();
      const conversations: GraphConversation[] = page.data || [];

      for (const conv of conversations) {
        conversationsSeen++;
        const participants = conv.participants?.data || [];
        const customer = participants.find((p) => p.id && p.id !== pageId);
        if (!customer?.id) continue; // couldn't tell who the customer is - skip rather than guess

        const psid = customer.id;

        const { error: upsertConvErr } = await supabase
          .from('ChatbotConversations')
          .upsert({ Psid: psid, PageId: pageId, CustomerName: customer.name || null }, { onConflict: 'Psid', ignoreDuplicates: true });
        if (!upsertConvErr) conversationsUpserted++;

        const rawMessages = conv.messages?.data || [];
        if (rawMessages.length === 0) conversationsWithNoMessages++;
        const rows: Record<string, unknown>[] = [];

        for (const msg of rawMessages) {
          if (!msg.id) continue;
          const isFromPage = msg.from?.id === pageId;
          const text = (msg.message || '').trim();

          let attachmentPath: string | null = null;
          let attachmentUrl: string | null = null;
          let attachmentType: string | null = null;
          const imageAttachment = msg.attachments?.data?.find((a) => a.image_data?.url);
          if (imageAttachment?.image_data?.url) {
            const stored = await downloadAndStoreImage(supabase, psid, imageAttachment.image_data.url);
            if (stored) {
              attachmentPath = stored.path;
              attachmentUrl = stored.signedUrl;
              attachmentType = 'image';
              imagesStored++;
            }
          }

          const content = text || (attachmentUrl ? '[Photo]' : '');
          if (!content) continue;

          rows.push({
            Psid: psid,
            Role: isFromPage ? 'staff' : 'user',
            Content: content,
            FacebookMessageId: msg.id,
            CreatedAtUtc: msg.created_time || new Date().toISOString(),
            AttachmentPath: attachmentPath,
            AttachmentUrl: attachmentUrl,
            AttachmentType: attachmentType
          });
        }

        if (rows.length > 0) {
          const { error: insertErr } = await supabase
            .from('ChatbotMessages')
            .upsert(rows, { onConflict: 'FacebookMessageId', ignoreDuplicates: true });
          if (insertErr) {
            console.error('Failed to backfill messages for psid', psid, insertErr.message);
          } else {
            messagesProcessed += rows.length;
          }
        }
      }

      const next = page.paging?.next;
      url = typeof next === 'string' ? next : null;
    }

    return jsonResponse({
      ok: true,
      conversationsSeen,
      conversationsUpserted,
      messagesProcessed,
      imagesStored,
      pagesFetched,
      conversationsWithNoMessages,
      note:
        conversationsWithNoMessages > 0
          ? `${conversationsWithNoMessages} conversation(s) synced but came back with zero messages - Facebook likely withheld the content because those customers aren't Testers/Admins on the app yet (Development Mode restriction). This should resolve once pages_messaging is approved with Advanced Access.`
          : undefined
    });
  } catch (err) {
    console.error('Unhandled error in facebook-conversations-backfill:', err instanceof Error ? err.message : err);
    return jsonResponse({ error: err instanceof Error ? err.message : 'Unexpected error.' }, 500);
  }
});
