using System;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Windows.Forms;

namespace AquariumPOS
{
    /// <summary>
    /// Simple Employee Setup form backed by dbo.EmployeeSetup.
    /// This form uses SELECT * FROM dbo.EmployeeSetup and a SqlDataAdapter + SqlCommandBuilder
    /// so it adapts to the table's current schema. It provides Add/Delete/Save/Close actions.
    /// Notes:
    /// - For SqlCommandBuilder to generate INSERT/UPDATE/DELETE the table should have a primary key.
    /// - This implementation is intentionally small and generic to avoid depending on a fixed schema.
    /// </summary>
    public class EmployeeSetupForm : Form
    {
        private DataGridView dgv = new DataGridView();
        private Button btnAdd = new Button();
        private Button btnDelete = new Button();
        private Button btnSave = new Button();
        private Button btnClose = new Button();

        private DataTable table = new DataTable();
        private SqlDataAdapter adapter = null!;
        private BindingSource binding = new BindingSource();
        private readonly string connectionString = GlobalSettings.ConnectionString;

        public EmployeeSetupForm()
        {
            Text = "Employee Setup";
            Size = new Size(900, 600);
            StartPosition = FormStartPosition.CenterParent;
            FormBorderStyle = FormBorderStyle.Sizable;
            InitializeComponent();
        }

        private void InitializeComponent()
        {
            dgv.Dock = DockStyle.Top;
            dgv.Height = ClientSize.Height - 80;
            dgv.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgv.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgv.MultiSelect = true;
            dgv.AllowUserToAddRows = false; // we'll use Add button

            btnAdd.Text = "Add";
            btnAdd.Size = new Size(100, 36);
            btnAdd.Location = new Point(10, ClientSize.Height - 70);
            btnAdd.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            btnAdd.Click += BtnAdd_Click;

            btnDelete.Text = "Delete";
            btnDelete.Size = new Size(100, 36);
            btnDelete.Location = new Point(120, ClientSize.Height - 70);
            btnDelete.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            btnDelete.Click += BtnDelete_Click;

            btnSave.Text = "Save";
            btnSave.Size = new Size(100, 36);
            btnSave.Location = new Point(230, ClientSize.Height - 70);
            btnSave.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            btnSave.Click += BtnSave_Click;

            btnClose.Text = "Close";
            btnClose.Size = new Size(100, 36);
            btnClose.Location = new Point(340, ClientSize.Height - 70);
            btnClose.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            btnClose.Click += (s, e) => Close();

            Controls.Add(dgv);
            Controls.AddRange(new Control[] { btnAdd, btnDelete, btnSave, btnClose });

            Load += EmployeeSetupForm_Load;
            Resize += (s, e) => { dgv.Height = ClientSize.Height - 80; };
        }

        private void EmployeeSetupForm_Load(object? sender, EventArgs e)
        {
            LoadData();
        }

        private void LoadData()
        {
            try
            {
                table.Clear();
                adapter = new SqlDataAdapter("SELECT * FROM dbo.EmployeeSetup", connectionString);
                adapter.MissingSchemaAction = MissingSchemaAction.AddWithKey;

                // First obtain schema (so identity/PK info is populated). This helps the DataTable
                // mark identity columns as AutoIncrement so adding rows client-side won't fail.
                try
                {
                    adapter.FillSchema(table, SchemaType.Source);
                }
                catch
                {
                    // best-effort; continue to Fill even if FillSchema fails on limited DB privileges
                }

                // CommandBuilder will auto-generate commands when possible
                var cb = new SqlCommandBuilder(adapter);

                adapter.Fill(table);

                binding.DataSource = table;
                dgv.DataSource = binding;

                // If the table has a boolean IsActive column, render it as a proper checkbox column
                var isActiveCol = table.Columns.Cast<DataColumn>().FirstOrDefault(c => string.Equals(c.ColumnName, "IsActive", StringComparison.OrdinalIgnoreCase));
                if (isActiveCol != null && isActiveCol.DataType == typeof(bool))
                {
                    // Replace the autogenerated text column with a DataGridViewCheckBoxColumn
                    if (dgv.Columns.Contains(isActiveCol.ColumnName))
                    {
                        int displayIndex = dgv.Columns[isActiveCol.ColumnName].DisplayIndex;
                        string headerText = dgv.Columns[isActiveCol.ColumnName].HeaderText;
                        dgv.Columns.Remove(isActiveCol.ColumnName);

                        var chk = new DataGridViewCheckBoxColumn()
                        {
                            Name = isActiveCol.ColumnName,
                            DataPropertyName = isActiveCol.ColumnName,
                            HeaderText = headerText,
                            ValueType = typeof(bool),
                            TrueValue = true,
                            FalseValue = false,
                            IndeterminateValue = false,
                            ThreeState = false,
                            AutoSizeMode = DataGridViewAutoSizeColumnMode.None,
                            Width = 80,
                        };
                        chk.DefaultCellStyle.NullValue = false;
                        dgv.Columns.Insert(Math.Min(displayIndex, dgv.Columns.Count), chk);
                    }
                    else
                    {
                        var chk = new DataGridViewCheckBoxColumn()
                        {
                            Name = isActiveCol.ColumnName,
                            DataPropertyName = isActiveCol.ColumnName,
                            HeaderText = isActiveCol.ColumnName,
                            ValueType = typeof(bool),
                            TrueValue = true,
                            FalseValue = false,
                            IndeterminateValue = false,
                            ThreeState = false,
                            AutoSizeMode = DataGridViewAutoSizeColumnMode.None,
                            Width = 80,
                        };
                        chk.DefaultCellStyle.NullValue = false;
                        dgv.Columns.Add(chk);
                    }
                }

                // If table has a primary key with ID column, hide heavy system columns if any
                foreach (DataGridViewColumn col in dgv.Columns)
                {
                    col.SortMode = DataGridViewColumnSortMode.NotSortable;
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Failed to load EmployeeSetup: {ex.Message}", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void BtnAdd_Click(object? sender, EventArgs e)
        {
            try
            {
                var newRow = table.NewRow();

                // If the table has an integer ID column, assign a sequential ID (start at 1)
                var idCol = table.Columns.Cast<DataColumn>().FirstOrDefault(c => string.Equals(c.ColumnName, "ID", StringComparison.OrdinalIgnoreCase));
                if (idCol != null && (idCol.DataType == typeof(int) || idCol.DataType == typeof(long)))
                {
                    // find max existing numeric id (including rows that may not yet be saved)
                    long maxId = 0;
                    foreach (DataRow r in table.Rows)
                    {
                        try
                        {
                            if (!r.IsNull(idCol))
                            {
                                var v = Convert.ToInt64(r[idCol]);
                                if (v > maxId) maxId = v;
                            }
                        }
                        catch { }
                    }
                    long nextId = maxId + 1;
                    // assign to new row (convert to appropriate type)
                    if (idCol.DataType == typeof(int)) newRow[idCol] = (int)nextId;
                    else newRow[idCol] = nextId;
                }

                // If an IsActive boolean column exists, default new rows to true (active)
                var isActiveCol = table.Columns.Cast<DataColumn>().FirstOrDefault(c => string.Equals(c.ColumnName, "IsActive", StringComparison.OrdinalIgnoreCase));
                if (isActiveCol != null && isActiveCol.DataType == typeof(bool))
                {
                    try { newRow[isActiveCol] = true; } catch { }
                }

                // For common required string columns, set empty string as a safe default.
                // This helps when DB columns are NOT NULL and the user hasn't typed yet.
                foreach (DataColumn col in table.Columns)
                {
                    try
                    {
                        if (col.DataType == typeof(string) && !col.AllowDBNull)
                        {
                            if (newRow.IsNull(col))
                                newRow[col] = string.Empty;
                        }
                    }
                    catch { }
                }

                // leave other fields empty/null to let user fill
                table.Rows.Add(newRow);
                binding.Position = binding.Count - 1;

                // Focus the first editable visible cell so the user can type immediately.
                var newGridRow = dgv.Rows[dgv.Rows.Count - 1];
                var firstEditable = newGridRow.Cells.Cast<DataGridViewCell>()
                    .FirstOrDefault(c => c.Visible && !c.ReadOnly);
                dgv.CurrentCell = firstEditable ?? newGridRow.Cells.Cast<DataGridViewCell>().FirstOrDefault(c => c.Visible) ?? null;
                dgv.BeginEdit(true);
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Failed to add row: {ex.Message}", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void BtnDelete_Click(object? sender, EventArgs e)
        {
            try
            {
                if (dgv.SelectedRows.Count == 0)
                {
                    MessageBox.Show("Please select one or more rows to delete.", "No selection", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    return;
                }

                var confirm = MessageBox.Show($"Delete {dgv.SelectedRows.Count} selected row(s)?", "Confirm Delete", MessageBoxButtons.YesNo, MessageBoxIcon.Question);
                if (confirm != DialogResult.Yes) return;

                foreach (DataGridViewRow r in dgv.SelectedRows)
                {
                    if (!r.IsNewRow)
                    {
                        dgv.Rows.Remove(r);
                    }
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Failed to delete rows: {ex.Message}", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void BtnSave_Click(object? sender, EventArgs e)
        {
            try
            {
                // End any current edits
                dgv.EndEdit();
                binding.EndEdit();

                if (adapter == null)
                {
                    adapter = new SqlDataAdapter("SELECT * FROM dbo.EmployeeSetup", connectionString);
                    adapter.MissingSchemaAction = MissingSchemaAction.AddWithKey;
                }

                // Ensure we have commands (recreate builder to be safe)
                var cb = new SqlCommandBuilder(adapter);

                var changes = table.GetChanges();
                if (changes == null)
                {
                    MessageBox.Show("No changes to save.", "Info", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    return;
                }

                adapter.Update(table);
                table.AcceptChanges();
                MessageBox.Show("Saved successfully.", "Saved", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Failed to save changes: {ex.Message}", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
    }
}
