-- SQL Server tables for persisting the Expense Report (mirrors the naming/style
-- conventions used for dbo.MonthEndHeader / dbo.MonthEndLines in
-- ItemVariantSalesWorksheetData.cs).
--
-- NOTE: The Expense Report is currently generated on the fly in
-- PostingEvents.cs (GenerateExpenseReportLines / PrintExpenseReport) directly
-- from TransactionHeader - it is not persisted anywhere today. This script
-- only creates the tables; wiring PrintExpenseReport to save into them would
-- be a separate follow-up change.

IF OBJECT_ID(N'dbo.ExpenseReportHeader', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.ExpenseReportHeader (
        [No.] NVARCHAR(50) NOT NULL PRIMARY KEY,
        [Generated Date] DATETIME2 NOT NULL,
        [From Date] DATE NOT NULL,
        [To Date] DATE NOT NULL,
        [Warehouse] NVARCHAR(200) NULL,
        [Generated By] NVARCHAR(100) NULL,
        [Total Lines] INT NOT NULL CONSTRAINT DF_ExpenseReportHeader_TotalLines DEFAULT (0),
        [Grand Total] DECIMAL(18, 2) NOT NULL CONSTRAINT DF_ExpenseReportHeader_GrandTotal DEFAULT (0),
        [Created AtUtc] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
    );
END;
GO

IF OBJECT_ID(N'dbo.ExpenseReportLines', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.ExpenseReportLines (
        [Document No.] NVARCHAR(50) NOT NULL,
        [Line No.] INT NOT NULL,
        [Category] NVARCHAR(100) NULL,
        [Description] NVARCHAR(500) NULL,
        [User ID] NVARCHAR(100) NULL,
        [Transaction Date] DATE NULL,
        [Transaction Time] NVARCHAR(20) NULL,
        [Quantity] DECIMAL(18, 2) NOT NULL CONSTRAINT DF_ExpenseReportLines_Quantity DEFAULT (0),
        [Amount] DECIMAL(18, 2) NOT NULL CONSTRAINT DF_ExpenseReportLines_Amount DEFAULT (0),
        [Created AtUtc] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK_ExpenseReportLines PRIMARY KEY ([Document No.], [Line No.]),
        CONSTRAINT FK_ExpenseReportLines_Header FOREIGN KEY ([Document No.])
            REFERENCES dbo.ExpenseReportHeader ([No.])
    );
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_ExpenseReportLines_Category' AND object_id = OBJECT_ID(N'dbo.ExpenseReportLines'))
BEGIN
    CREATE INDEX IX_ExpenseReportLines_Category ON dbo.ExpenseReportLines ([Category]);
END;
GO
