-- ONE-TIME manual setup - run this in the Supabase SQL editor with the placeholder below replaced
-- by your actual Supabase secret/service-role key (Project Settings -> API -> Secret keys).
--
-- DO NOT commit this file with a real key filled in - paste the real value directly into the SQL
-- editor, run it there, then leave this file in the repo with the placeholder intact. This is
-- what supabase_fix_storage_signed_upload_key.sql / supabase_online_order_line_attachments.sql /
-- supabase_portal_logo_upload.sql now read via current_setting('app.settings.
-- supabase_service_role_key', true) instead of a hardcoded literal - GitHub's push protection
-- blocks any commit containing a live Supabase secret key, and a hardcoded value would just get
-- re-leaked the next time one of those files changes anyway.
--
-- Applies to NEW database connections going forward (a Postgres database-level setting, not a
-- session-level one) - if uploads still fail with "is not configured" right after running this,
-- give Supabase's connection pooler a minute to cycle to a fresh connection, or restart the
-- project's API from the Supabase dashboard (Project Settings -> General -> Restart project).
--
-- If you ever need to rotate this key again: just re-run this same ALTER DATABASE with the new
-- value - no code changes needed anywhere.
alter database postgres set app.settings.supabase_service_role_key = '<PASTE_YOUR_SUPABASE_SECRET_KEY_HERE>';
