-- Postgres/Supabase version of the local dbo.CompleteAquariumSetHeader /
-- dbo.CompleteAquariumSetLine tables (Customer Aquarium package builder),
-- created for the Web Portal (WebPortal/customer-aquarium.html).
--
-- Run this in the Supabase SQL Editor.
--
-- NOTE: These are new Supabase tables - packages created/edited on the web
-- portal live here. The local desktop app does NOT currently push its
-- existing packages into these tables, so the portal will start empty. Ask
-- for a follow-up sync if you want existing local packages mirrored here.

create table if not exists public."CompleteAquariumSetHeader" (
    "PackageName" varchar(100) not null primary key,
    "PackagePrice" numeric(18, 2) not null default 0,
    "VariantID" varchar(200),
    "CreatedDate" timestamptz not null default timezone('utc', now()),
    "UpdatedDate" timestamptz not null default timezone('utc', now())
);

create table if not exists public."CompleteAquariumSetLine" (
    "EntryNo" bigint generated by default as identity primary key,
    "PackageName" varchar(100) not null references public."CompleteAquariumSetHeader" ("PackageName") on delete cascade,
    "ItemNo" varchar(50) not null default '',
    "ItemName" varchar(255),
    "Quantity" numeric(18, 2) not null default 1,
    "Price" numeric(18, 2) not null default 0,
    "CreatedDate" timestamptz not null default timezone('utc', now()),
    "UpdatedDate" timestamptz not null default timezone('utc', now())
);

create index if not exists "IX_CompleteAquariumSetLine_PackageName"
    on public."CompleteAquariumSetLine" ("PackageName");

comment on table public."CompleteAquariumSetHeader" is 'Web Portal copy of AquariumPOS local dbo.CompleteAquariumSetHeader (customer aquarium package definitions).';
comment on table public."CompleteAquariumSetLine" is 'Web Portal copy of AquariumPOS local dbo.CompleteAquariumSetLine (package line items).';
