-- Resyncs ItemSerialTracking.RunningSerialNo's identity sequence with the table's real max value.
--
-- Why this is needed: until the recent fix to LoadItemSerialTrackingRows (OnlinefunctionsEvents.cs),
-- every row pushed from a store's desktop app INSERTed an explicit RunningSerialNo (that store's own
-- local IDENTITY value) instead of leaving Supabase's "generated by default as identity" column to
-- assign its own. Postgres does NOT advance an identity column's underlying sequence when a value is
-- supplied explicitly - only when the column itself generates it. So the sequence here was left far
-- behind (likely still at or near its starting point), while the table itself already holds rows with
-- RunningSerialNo values in the tens of thousands from every store's own explicit inserts.
--
-- With the C# push now omitting RunningSerialNo so Postgres assigns nextval() on every new row, that
-- call was still handing out numbers the table already has (e.g. nextval() = 1, but a row with
-- RunningSerialNo = 1 already exists) - hence the sync continuing to fail with "duplicate key value
-- violates unique constraint ItemSerialTracking_pkey" even after that code fix. Run this once to move
-- the sequence past the table's current max; every insert after that gets a value nothing has used.
select setval(
  pg_get_serial_sequence('public."ItemSerialTracking"', 'RunningSerialNo'),
  (select coalesce(max("RunningSerialNo"), 0) from public."ItemSerialTracking")
);
