-- Supabase/Postgres version of the local dbo.ItemSerialTracking table.
-- This keeps the same table and column names as the C# solution to reduce mapping work.

create table if not exists public."ItemSerialTracking" (
    "RunningSerialNo" bigint generated by default as identity primary key,
    "SerialNo" varchar(120) not null,
    "ItemCode" varchar(100) not null,
    "ItemDescription" varchar(255),
    "Location" varchar(255),
    "Status" varchar(255) not null default 'IN_STOCK',
    "SourceDocumentNo" varchar(100),
    "CreatedAtUtc" timestamptz not null default timezone('utc', now()),
    "CreatedBy" varchar(100),
    "UpdatedAtUtc" timestamptz,
    "VariantCode" varchar(200),
    "SoldReceiptNo" varchar(100),
    "SoldOnlineOrderId" varchar(100)
);

create unique index if not exists "UX_ItemSerialTracking_SerialNo"
    on public."ItemSerialTracking" ("SerialNo");

create index if not exists "IX_ItemSerialTracking_ItemCode_Status"
    on public."ItemSerialTracking" ("ItemCode", "Status");

create index if not exists "IX_ItemSerialTracking_ItemCode_VariantCode_Status"
    on public."ItemSerialTracking" ("ItemCode", "VariantCode", "Status");

alter table public."ItemSerialTracking"
    add column if not exists "VariantCode" varchar(200);

alter table public."ItemSerialTracking"
    add column if not exists "Location" varchar(255);

alter table public."ItemSerialTracking"
    add column if not exists "SoldReceiptNo" varchar(100);

alter table public."ItemSerialTracking"
    add column if not exists "SoldOnlineOrderId" varchar(100);

alter table public."ItemSerialTracking"
    alter column "Status" type varchar(255);

comment on table public."ItemSerialTracking" is 'Supabase copy of the AquariumPOS local serial tracking table.';
comment on column public."ItemSerialTracking"."RunningSerialNo" is 'Identity primary key matching local RunningSerialNo.';
comment on column public."ItemSerialTracking"."SerialNo" is 'Unique serial number shown on labels and assigned to sales/orders.';
comment on column public."ItemSerialTracking"."Location" is 'Current warehouse or location name captured when the serial record was created.';
comment on column public."ItemSerialTracking"."Status" is 'Expected values include IN_STOCK and SOLD.';