-- SET package explosion on the portal's To Ship - per "is it possible to apply this routine into the
-- Portal too??" (Phase 1). Ports the desktop POS's PrepareSetAssemblyForOrder (OnlineOrdersForm.cs):
-- when an order has a line whose category is SET, staff pick the BOM package for it (once per product,
-- remembered), review the package's components (swap variants, change quantities, drop a component),
-- and the components are added to the Pancake order as extra lines at price 0 - so the order total does
-- not change but Pancake (and everything that reads its lines: stock, serials, ledger) sees the parts.
--
-- What this adds:
--   1. public."OnlineOrderSetPackageMap" - the portal copy of the POS's local dbo.OnlineOrderSetPackageMap
--      (VariationId/ItemCode -> PackageName). Starts empty; fills as staff map lines on the portal.
--   2. staff_get_online_order_set_assembly(order): re-reads the order from Pancake, then returns its SET
--      lines, the package each resolves to (or null = staff must pick), each package's components with
--      variant options + defaults, and the list of packages to pick from.
--   3. staff_get_set_package_components(package, set qty): components for a package picked in the dialog.
--   4. staff_save_online_order_set_materials(order, sets): rebuilds the Pancake order's items - drops the
--      old "SET Material for <set>" lines, writes "SET Materials: ..." on the SET line's note, appends the
--      new component lines (price 0) - PATCHes Pancake (PUT on 404/405, bank_payments restored), then
--      re-reads the order so OnlineOrderLines matches Pancake.
--
-- Same conventions as the POS, so a POS run and a portal run on the same order replace each other's
-- materials instead of doubling them: component note "SET Material for <SET line name>", SET line note
-- line "SET Materials: <name> x <qty>; ...".
--
-- Differences from the POS (on purpose):
--   - The item list is built from Pancake's OWN copy of the order (GET), not from local lines, so per-item
--     discounts / wholesale / bonus flags and one-time products on the other lines are sent back as they
--     were (the POS resets discounts to 0 and turns one-time products into catalog products).
--   - Every component must resolve to a Pancake product (VariationId) or the save is refused - a
--     one-time product would never deduct stock, which is the point of exploding.
--   - Package matching uses the Supabase copy of the packages (CompleteAquariumSetHeader/Line, edited on
--     the Customer Aquarium page). The POS reads its own LOCAL copy - the two are NOT synced.
--
-- Add-ons (section 6): Media (up to 5) / Light / Pump / Pipe / Mesh Bag items NOT in the package can be added
-- in the dialog, like the POS's accessory slots.
--
-- Run AFTER supabase_online_order_sync_no_long_locks.sql and supabase_online_order_refresh_lines_before_ship.sql.
-- Creates the package tables itself if supabase_customer_aquarium_tables.sql was never run (they start
-- empty - copy the POS's packages over with local_export_complete_aquarium_sets.sql). Safe to re-run.

-- ---------------------------------------------------------------------------
-- 0. Package tables (same as supabase_customer_aquarium_tables.sql + its policies in
--    supabase_web_portal_rls_policies.sql - the Customer Aquarium page reads/writes them directly).
create table if not exists public."CompleteAquariumSetHeader" (
    "PackageName" varchar(100) not null primary key,
    "PackagePrice" numeric(18, 2) not null default 0,
    "VariantID" varchar(200),
    "CreatedDate" timestamptz not null default timezone('utc', now()),
    "UpdatedDate" timestamptz not null default timezone('utc', now())
);

create table if not exists public."CompleteAquariumSetLine" (
    "EntryNo" bigint generated by default as identity primary key,
    "PackageName" varchar(100) not null references public."CompleteAquariumSetHeader" ("PackageName") on delete cascade,
    "ItemNo" varchar(50) not null default '',
    "ItemName" varchar(255),
    "Quantity" numeric(18, 2) not null default 1,
    "Price" numeric(18, 2) not null default 0,
    "CreatedDate" timestamptz not null default timezone('utc', now()),
    "UpdatedDate" timestamptz not null default timezone('utc', now())
);

create index if not exists "IX_CompleteAquariumSetLine_PackageName"
    on public."CompleteAquariumSetLine" ("PackageName");

alter table public."CompleteAquariumSetHeader" enable row level security;
drop policy if exists "Anon full access" on public."CompleteAquariumSetHeader";
create policy "Anon full access" on public."CompleteAquariumSetHeader"
    for all to anon, authenticated using (true) with check (true);

alter table public."CompleteAquariumSetLine" enable row level security;
drop policy if exists "Anon full access" on public."CompleteAquariumSetLine";
create policy "Anon full access" on public."CompleteAquariumSetLine"
    for all to anon, authenticated using (true) with check (true);

-- ---------------------------------------------------------------------------
-- 1. Package mapping.
create table if not exists public."OnlineOrderSetPackageMap" (
  "MatchType" varchar(50) not null,          -- 'VariationId' or 'ItemCode'
  "MatchValue" varchar(200) not null,
  "PackageName" varchar(100) not null,
  "SourceDescription" varchar(255),
  "UpdatedDate" timestamptz not null default now(),
  constraint "PK_OnlineOrderSetPackageMap" primary key ("MatchType", "MatchValue")
);

alter table public."OnlineOrderSetPackageMap" enable row level security;
revoke all on public."OnlineOrderSetPackageMap" from anon, authenticated;

-- ---------------------------------------------------------------------------
-- 2. Helpers.

-- Category of an order line: Variants by VariationId, then Items by VariationId, then Items by code
-- (same order as OnlineOrdersForm.cs ResolveOnlineLineCategoryCode).
create or replace function public._online_order_line_category(p_variation_id text, p_item_code text)
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select trim(v."CategoryCode") from public."Variants" v
      where nullif(trim(p_variation_id), '') is not null
        and v."VariationId" = trim(p_variation_id)
        and nullif(trim(v."CategoryCode"), '') is not null
      limit 1),
    (select trim(i."CategoryCode") from public."Items" i
      where nullif(trim(p_variation_id), '') is not null
        and i."VariationId" = trim(p_variation_id)
        and nullif(trim(i."CategoryCode"), '') is not null
      limit 1),
    (select trim(i."CategoryCode") from public."Items" i
      where nullif(trim(p_item_code), '') is not null
        and (i."Code" = trim(p_item_code) or i."VariationId" = trim(p_item_code))
        and nullif(trim(i."CategoryCode"), '') is not null
      limit 1),
    ''
  );
$$;

create or replace function public._set_package_has_lines(p_package text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public."CompleteAquariumSetLine" l
    where lower(trim(l."PackageName")) = lower(trim(p_package))
      and trim(coalesce(l."ItemNo", '')) <> ''
  );
$$;

-- Package for a SET line: header VariantID = VariationId, then a saved mapping by VariationId, then by
-- ItemCode (OnlineOrdersForm.cs TryResolveSetPackageMapping). Only packages that have BOM lines count.
create or replace function public._resolve_set_package(p_variation_id text, p_item_code text)
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select h."PackageName" from public."CompleteAquariumSetHeader" h
      where nullif(trim(p_variation_id), '') is not null
        and lower(trim(coalesce(h."VariantID", ''))) = lower(trim(p_variation_id))
        and public._set_package_has_lines(h."PackageName")
      order by h."PackageName"
      limit 1),
    (select h."PackageName" from public."OnlineOrderSetPackageMap" m
      join public."CompleteAquariumSetHeader" h on lower(trim(h."PackageName")) = lower(trim(m."PackageName"))
      where nullif(trim(p_variation_id), '') is not null
        and m."MatchType" = 'VariationId' and m."MatchValue" = trim(p_variation_id)
        and public._set_package_has_lines(h."PackageName")
      limit 1),
    (select h."PackageName" from public."OnlineOrderSetPackageMap" m
      join public."CompleteAquariumSetHeader" h on lower(trim(h."PackageName")) = lower(trim(m."PackageName"))
      where nullif(trim(p_item_code), '') is not null
        and m."MatchType" = 'ItemCode' and m."MatchValue" = trim(p_item_code)
        and public._set_package_has_lines(h."PackageName")
      limit 1)
  );
$$;

-- A package's components for p_set_qty sets: quantity = BOM qty x set qty (truncated, as the POS does),
-- the variant options of each component's main product and the default pick (exact code, exact name,
-- name contains, or the only variant - MainForm.cs FindDefaultAquariumVariantSelection).
-- requires_choice = has variants but none matched, so staff must pick one. sealant_choice = the variants
-- are Black / Clear sealant: never defaulted, staff pick the colour at Ready to Ship.
create or replace function public._set_package_components(p_package text, p_set_qty int)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_line record;
  v_item_no text;
  v_item_name text;
  v_main_code text;
  v_variants jsonb;
  v_default jsonb;
  v_base_variation text;
  v_sealant boolean;
  v_result jsonb := '[]'::jsonb;
begin
  for v_line in
    select l.* from public."CompleteAquariumSetLine" l
    where lower(trim(l."PackageName")) = lower(trim(p_package))
      and trim(coalesce(l."ItemNo", '')) <> ''
    order by l."EntryNo"
  loop
    v_item_no := trim(v_line."ItemNo");
    v_item_name := coalesce(nullif(trim(v_line."ItemName"), ''), v_item_no);
    v_main_code := null;
    v_base_variation := null;
    v_sealant := false;

    select coalesce(nullif(trim(v."MainItemCode"), ''), v_item_no) into v_main_code
    from public."Variants" v
    where v."MainItemCode" = v_item_no or v."ItemCode" = v_item_no
    order by (v."MainItemCode" = v_item_no) desc, v."VariationId"
    limit 1;
    v_main_code := coalesce(v_main_code, v_item_no);

    select coalesce(jsonb_agg(x order by x ->> 'name', x ->> 'item_code'), '[]'::jsonb) into v_variants
    from (
      select distinct on (v."VariationId") jsonb_build_object(
        'variation_id', v."VariationId",
        'item_code', coalesce(nullif(trim(v."ItemCode"), ''), v."MainItemCode"),
        'name', coalesce(nullif(trim(v."VariantName"), ''), nullif(trim(vi."Name"), ''), nullif(trim(vi."Description"), ''),
                         coalesce(nullif(trim(v."ItemCode"), ''), v."MainItemCode")),
        'description', coalesce(nullif(trim(vi."Description"), ''), nullif(trim(mi."Description"), ''), ''),
        'variant_name', coalesce(nullif(trim(v."VariantName"), ''), ''),
        'sku', coalesce(nullif(trim(v."SKU"), ''), nullif(trim(vi."SKU"), ''), ''),
        'price', coalesce(v."Price", vi."Price", mi."Price", v_line."Price")
      ) as x
      from public."Variants" v
      left join public."Items" vi on vi."Code" = coalesce(nullif(trim(v."ItemCode"), ''), v."MainItemCode")
      left join public."Items" mi on mi."Code" = v."MainItemCode"
      where v."MainItemCode" = v_main_code
      order by v."VariationId"
    ) s;

    v_default := null;
    if jsonb_array_length(v_variants) > 0 then
      -- SKU first: variants of one product share the item code (AST-011-BlackPaint / -WhitePaint), and
      -- the package line's name is usually the exact SKU.
      select x into v_default from jsonb_array_elements(v_variants) x
      where x ->> 'sku' <> '' and lower(x ->> 'sku') in (lower(v_item_name), lower(v_item_no)) limit 1;
      if v_default is null then
        select x into v_default from jsonb_array_elements(v_variants) x
        where lower(x ->> 'item_code') = lower(v_item_no) limit 1;
      end if;
      if v_default is null then
        select x into v_default from jsonb_array_elements(v_variants) x
        where lower(x ->> 'name') = lower(v_item_name) or lower(x ->> 'description') = lower(v_item_name) limit 1;
      end if;
      if v_default is null then
        select x into v_default from jsonb_array_elements(v_variants) x
        where position(lower(v_item_name) in lower(x ->> 'name')) > 0
           or (x ->> 'name' <> '' and position(lower(x ->> 'name') in lower(v_item_name)) > 0)
        limit 1;
      end if;
      if v_default is null and jsonb_array_length(v_variants) = 1 then
        v_default := v_variants -> 0;
      end if;
      -- Black / Clear sealant variants (same rule as the Sealant Sales report): no default - staff
      -- choose the colour at Ready to Ship; the stock check counts either colour.
      -- Also when the package line itself names a sealant (e.g. "AQ-021-BlackSealant") and the product
      -- has more than one variant - the colour on the package line is only an example, staff choose.
      v_sealant := (select count(*) from jsonb_array_elements(v_variants) x
                    where (coalesce(x ->> 'name', '') || ' ' || coalesce(x ->> 'variant_name', '') || ' ' || coalesce(x ->> 'sku', '')) ~* 'sealant'
                      and (coalesce(x ->> 'name', '') || ' ' || coalesce(x ->> 'variant_name', '') || ' ' || coalesce(x ->> 'sku', '')) ~* '(black|clear)') >= 2
                   or (v_item_name ~* 'sealant' and jsonb_array_length(v_variants) >= 2);
      if v_sealant then
        v_default := null;
      end if;
    else
      select nullif(trim(i."VariationId"), '') into v_base_variation
      from public."Items" i where i."Code" = v_item_no limit 1;
      v_default := jsonb_build_object(
        'variation_id', v_base_variation,
        'item_code', v_item_no,
        'name', v_item_name,
        'description', coalesce((select nullif(trim(i."Description"), '') from public."Items" i where i."Code" = v_item_no limit 1), v_item_name),
        'variant_name', '',
        'sku', coalesce((select nullif(trim(i."SKU"), '') from public."Items" i where i."Code" = v_item_no limit 1), ''),
        'price', v_line."Price"
      );
    end if;

    v_result := v_result || jsonb_build_array(jsonb_build_object(
      'bom_item_no', v_item_no,
      'bom_item_name', v_item_name,
      'main_item_code', v_main_code,
      'sealant_choice', v_sealant,
      'qty_per', v_line."Quantity",
      'quantity', trunc(v_line."Quantity" * greatest(p_set_qty, 1)),
      'variants', v_variants,
      'default', v_default,
      'requires_choice', jsonb_array_length(v_variants) > 0 and v_default is null
    ));
  end loop;

  return v_result;
end;
$$;

revoke all on function public._online_order_line_category(text, text) from public, anon, authenticated;
revoke all on function public._set_package_has_lines(text) from public, anon, authenticated;
revoke all on function public._resolve_set_package(text, text) from public, anon, authenticated;
revoke all on function public._set_package_components(text, int) from public, anon, authenticated;

-- In Stock serials of one item / variant at a warehouse (same match as the stock check).
create or replace function public._set_serials_in_stock(p_item_code text, p_variation_id text, p_warehouse text)
returns int
language sql
stable
security definer
set search_path = public
as $$
  select count(*)::int from public."ItemSerialTracking" s
  where s."Status" = 'IN_STOCK'
    and s."Location" = p_warehouse
    and s."ItemCode" = p_item_code
    and coalesce(nullif(trim(s."VariantCode"), ''), '') = coalesce(nullif(trim(p_variation_id), ''), '');
$$;

-- Adds stock to _set_package_components' output for the order's branch (per "only show the item with
-- available serials"): each component gets 'serial_tracked' (a production item - AQ-% code or a production
-- category, same rule as the stock check) and, when tracked, each variant / the default gets 'in_stock'.
-- The dialog then lists only the variants with serials in stock. No warehouse -> unchanged.
create or replace function public._set_components_add_stock(p_components jsonb, p_warehouse text)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(jsonb_agg(
    case when not t.tracked or p_warehouse is null then c || jsonb_build_object('serial_tracked', t.tracked)
    else c || jsonb_build_object(
      'serial_tracked', true,
      'variants', (select coalesce(jsonb_agg(
                     v || jsonb_build_object('in_stock', public._set_serials_in_stock(v ->> 'item_code', v ->> 'variation_id', p_warehouse))
                     order by vo), '[]'::jsonb)
                   from jsonb_array_elements(coalesce(c -> 'variants', '[]'::jsonb)) with ordinality as ve(v, vo)),
      'default', case when jsonb_typeof(c -> 'default') = 'object'
                      then (c -> 'default') || jsonb_build_object('in_stock',
                             public._set_serials_in_stock(c -> 'default' ->> 'item_code', c -> 'default' ->> 'variation_id', p_warehouse))
                      else c -> 'default' end)
    end
    order by o), '[]'::jsonb)
  from jsonb_array_elements(coalesce(p_components, '[]'::jsonb)) with ordinality as e(c, o)
  cross join lateral (
    select upper(coalesce(c -> 'default' ->> 'item_code', c -> 'variants' -> 0 ->> 'item_code', c ->> 'bom_item_no', '')) like 'AQ-%'
        or coalesce((select cat."IsProductionCategory" from public."Categories" cat
                     where cat."Code" = nullif(public._online_order_line_category(
                       coalesce(c -> 'default' ->> 'variation_id', c -> 'variants' -> 0 ->> 'variation_id'),
                       coalesce(c -> 'default' ->> 'item_code', c -> 'variants' -> 0 ->> 'item_code', c ->> 'bom_item_no')), '')
                     limit 1), false) as tracked
  ) t;
$$;

-- The order's branch name (what ItemSerialTracking."Location" holds).
create or replace function public._online_order_warehouse_name(p_order_id text)
returns text
language sql
stable
security definer
set search_path = public
as $$
  select w."Name"::text from public."OnlineOrders" o
  join public."Warehouses" w on w."ID" = o."LocationID"
  where o."OrderID"::text = p_order_id
  limit 1;
$$;

revoke all on function public._set_serials_in_stock(text, text, text) from public, anon, authenticated;
revoke all on function public._set_components_add_stock(jsonb, text) from public, anon, authenticated;
revoke all on function public._online_order_warehouse_name(text) from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- 3. What the To Ship dialog needs. Re-reads the order from Pancake first (same as
--    staff_refresh_online_order_lines), so the caller can skip its own refresh afterwards.
--    { sets: [...], packages: [names] } - sets is empty when the order has no SET line.
create or replace function public.staff_get_online_order_set_assembly(
  p_admin_username text,
  p_admin_password text,
  p_order_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
set statement_timeout = '30000'
as $$
declare
  v_line record;
  v_item_code text;
  v_package text;
  v_qty numeric;
  v_display text;
  v_sets jsonb := '[]'::jsonb;
  v_packages jsonb;
begin
  if not public.is_staff_authorized(p_admin_username, p_admin_password) then
    raise exception 'Not authorized.';
  end if;
  if p_order_id is null or trim(p_order_id) = '' then
    raise exception 'Order ID is required.';
  end if;

  perform extensions.http_set_curlopt('CURLOPT_TIMEOUT_MS', '15000');
  begin
    perform public._sync_online_order_detail(p_order_id);
  exception when others then
    raise exception 'Could not re-read order % from Pancake (%). Please try again in a moment.', p_order_id, sqlerrm;
  end;

  for v_line in
    select * from public."OnlineOrderLines"
    where "OrderID" = p_order_id and "LineID" not like '%~SETMAT~%'
    order by "LineID"
  loop
    v_item_code := coalesce(nullif(trim(v_line."ItemCode"), ''), nullif(trim(v_line."product_display_id"), ''));
    if upper(public._online_order_line_category(v_line."VariationId", v_item_code)) <> 'SET' then
      continue;
    end if;

    v_package := public._resolve_set_package(v_line."VariationId", v_item_code);
    v_qty := coalesce(v_line."Quantity", 0);
    v_display := coalesce(nullif(trim(v_line."Description"), ''), v_item_code, v_line."VariationId", 'SET Line ' || v_line."LineID");

    v_sets := v_sets || jsonb_build_array(jsonb_build_object(
      'line_id', v_line."LineID",
      'item_code', v_item_code,
      'variation_id', v_line."VariationId",
      'description', v_display,
      'quantity', v_qty,
      'note', v_line."Note",
      'package_name', v_package,
      -- Already assembled (its "SET Material for ..." lines are on the order) - To Ship skips it; the
      -- Assemble button can still redo it.
      'exploded', exists (
        select 1 from public."OnlineOrderLines" m
        where m."OrderID" = p_order_id and trim(coalesce(m."Note", '')) = 'SET Material for ' || v_display),
      'components', case
        when v_package is not null and v_qty > 0 and v_qty = trunc(v_qty)
          then public._set_components_add_stock(public._set_package_components(v_package, v_qty::int),
                                                public._online_order_warehouse_name(p_order_id))
        else null
      end
    ));
  end loop;

  select coalesce(jsonb_agg(h."PackageName" order by h."PackageName"), '[]'::jsonb) into v_packages
  from public."CompleteAquariumSetHeader" h
  where public._set_package_has_lines(h."PackageName");

  return jsonb_build_object('sets', v_sets, 'packages', v_packages);
end;
$$;

grant execute on function public.staff_get_online_order_set_assembly(text, text, text) to anon;

-- ---------------------------------------------------------------------------
-- 4. Components of a package picked in the dialog. p_order_id: count serials at that order's branch.
drop function if exists public.staff_get_set_package_components(text, text, text, int);

create or replace function public.staff_get_set_package_components(
  p_admin_username text,
  p_admin_password text,
  p_package_name text,
  p_set_qty int,
  p_order_id text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_staff_authorized(p_admin_username, p_admin_password) then
    raise exception 'Not authorized.';
  end if;
  if p_package_name is null or not public._set_package_has_lines(p_package_name) then
    raise exception 'Package "%" has no BOM lines.', coalesce(p_package_name, '');
  end if;
  return public._set_components_add_stock(
    public._set_package_components(p_package_name, greatest(coalesce(p_set_qty, 1), 1)),
    public._online_order_warehouse_name(p_order_id));
end;
$$;

grant execute on function public.staff_get_set_package_components(text, text, text, int, text) to anon;

-- ---------------------------------------------------------------------------
-- 5. Save: rebuild the Pancake order's items with the SET materials.
--    p_sets: [ { line_id, package_name, save_mapping: bool,
--                materials: [ { item_code, variation_id, name, quantity } ] } ]
create or replace function public.staff_save_online_order_set_materials(
  p_admin_username text,
  p_admin_password text,
  p_order_id text,
  p_sets jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
set statement_timeout = '45000'
as $$
declare
  v_url text;
  v_get_response extensions.http_response;
  v_get_body jsonb;
  v_order_obj jsonb;
  v_bank_payments jsonb;
  v_set jsonb;
  v_set_idx int;
  v_mat jsonb;
  v_parent record;
  v_display text;
  v_material_note text;
  v_summary text;
  v_kept_note text;
  v_mat_qty numeric;
  v_mat_variation text;
  v_mat_code text;
  v_mat_name text;
  v_next_ord int;
  v_material_count int := 0;
  v_items jsonb;
  v_body jsonb;
  v_patch_response extensions.http_response;
  v_put_response extensions.http_response;
  v_resynced boolean := true;
begin
  if not public.is_staff_authorized(p_admin_username, p_admin_password) then
    raise exception 'Not authorized.';
  end if;
  if p_order_id is null or trim(p_order_id) = '' then
    raise exception 'Order ID is required.';
  end if;
  if p_sets is null or jsonb_typeof(p_sets) <> 'array' or jsonb_array_length(p_sets) = 0 then
    raise exception 'No SET lines were sent.';
  end if;

  v_url := 'https://pos.pages.fm/api/v1/shops/1328301944/orders/' || trim(p_order_id)
    || '?api_key=' || public._pancake_api_key() || '&page_size=1000';

  perform extensions.http_set_curlopt('CURLOPT_TIMEOUT_MS', '15000');
  perform extensions.http_set_curlopt('CURLOPT_USERAGENT', 'RSPetStopPortal/1.0');

  -- Pancake's current copy of the order is the base - the update replaces ALL items, so a failed read
  -- must stop here rather than push a partial list.
  v_get_response := extensions.http_get(v_url);
  if v_get_response.status < 200 or v_get_response.status >= 300 then
    raise exception 'Could not read order % from Pancake (HTTP %). Please try again.', p_order_id, v_get_response.status;
  end if;
  v_get_body := v_get_response.content::jsonb;
  v_order_obj := case
    when jsonb_typeof(v_get_body -> 'data') = 'object' then v_get_body -> 'data'
    when jsonb_typeof(v_get_body -> 'order') = 'object' then v_get_body -> 'order'
    else v_get_body
  end;
  if jsonb_typeof(v_order_obj -> 'items') <> 'array' or jsonb_array_length(v_order_obj -> 'items') = 0 then
    raise exception 'Pancake returned no items for order % - nothing was changed.', p_order_id;
  end if;
  if jsonb_typeof(v_order_obj -> 'bank_payments') = 'object' then
    v_bank_payments := v_order_obj -> 'bank_payments';
  end if;

  create temp table if not exists _set_explode_items (
    ord int,
    line_id text,
    variation_id text,
    item_code text,
    name text,
    detail text,
    quantity numeric,
    price numeric,
    note text,
    discount jsonb,
    is_bonus jsonb,
    is_discount_percent jsonb,
    is_wholesale jsonb,
    set_idx int,                               -- new component rows: which p_sets entry added them
    removed boolean not null default false
  ) on commit drop;
  truncate _set_explode_items;

  insert into _set_explode_items (ord, line_id, variation_id, item_code, name, detail, quantity, price, note,
                                  discount, is_bonus, is_discount_percent, is_wholesale)
  select
    e.ord::int,
    nullif(coalesce(it ->> 'line_id', it ->> 'id', it ->> 'order_line_id', it ->> 'order_item_id', it ->> 'item_id'), ''),
    nullif(trim(coalesce(it -> 'variation_info' ->> 'variation_id', it ->> 'variation_id', it ->> 'variationId', '')), ''),
    nullif(trim(coalesce(it -> 'variation_info' ->> 'product_display_id', it ->> 'product_display_id',
                         it -> 'variation_info' ->> 'display_id', '')), ''),
    nullif(trim(coalesce(it -> 'variation_info' ->> 'name', it ->> 'name', '')), ''),
    coalesce(it -> 'variation_info' ->> 'detail', it -> 'variation_info' ->> 'name', it ->> 'name'),
    public.pancake_parse_decimal(it ->> 'quantity'),
    public.pancake_parse_decimal(coalesce(it -> 'variation_info' ->> 'retail_price', it ->> 'retail_price')),
    it ->> 'note',
    case when jsonb_typeof(it -> 'discount_each_product') = 'number' then it -> 'discount_each_product' else '0'::jsonb end,
    case when jsonb_typeof(it -> 'is_bonus_product') = 'boolean' then it -> 'is_bonus_product' else 'false'::jsonb end,
    case when jsonb_typeof(it -> 'is_discount_percent') = 'boolean' then it -> 'is_discount_percent' else 'false'::jsonb end,
    case when jsonb_typeof(it -> 'is_wholesale') = 'boolean' then it -> 'is_wholesale' else 'false'::jsonb end
  from jsonb_array_elements(v_order_obj -> 'items') with ordinality as e(it, ord);

  for v_set, v_set_idx in select e.value, e.ord::int from jsonb_array_elements(p_sets) with ordinality as e(value, ord)
  loop
    select * into v_parent from _set_explode_items
    where line_id = v_set ->> 'line_id' and not removed
    limit 1;
    if not found then
      raise exception 'SET line % is no longer on order % in Pancake - close and reopen the order, then try again.',
        coalesce(v_set ->> 'line_id', '?'), p_order_id;
    end if;

    if not public._set_package_has_lines(v_set ->> 'package_name') then
      raise exception 'Package "%" has no BOM lines.', coalesce(v_set ->> 'package_name', '');
    end if;

    -- Same display text as the POS's BuildSetLineDisplayText (Description, ItemCode, VariationId).
    v_display := coalesce(v_parent.name, v_parent.item_code, v_parent.variation_id, 'SET Line ' || v_parent.line_id);
    v_material_note := 'SET Material for ' || v_display;

    -- Old materials of this SET (from an earlier portal or POS run) - Pancake's rows only, never the
    -- component rows this call just added for another SET line with the same name.
    update _set_explode_items set removed = true
    where trim(coalesce(note, '')) = v_material_note
      and set_idx is null
      and line_id is distinct from v_parent.line_id;

    if coalesce((v_set ->> 'save_mapping')::boolean, false) then
      insert into public."OnlineOrderSetPackageMap" ("MatchType", "MatchValue", "PackageName", "SourceDescription", "UpdatedDate")
      values (
        case when v_parent.variation_id is not null then 'VariationId' else 'ItemCode' end,
        coalesce(v_parent.variation_id, v_parent.item_code),
        trim(v_set ->> 'package_name'),
        left(v_display, 255),
        now()
      )
      on conflict ("MatchType", "MatchValue") do update
        set "PackageName" = excluded."PackageName",
            "SourceDescription" = excluded."SourceDescription",
            "UpdatedDate" = now();
    end if;

    select coalesce(max(ord), 0) into v_next_ord from _set_explode_items;

    for v_mat in select * from jsonb_array_elements(coalesce(v_set -> 'materials', '[]'::jsonb))
    loop
      v_mat_qty := public.pancake_parse_decimal(v_mat ->> 'quantity');
      if v_mat_qty is null or v_mat_qty <= 0 then
        continue;
      end if;

      v_mat_code := nullif(trim(coalesce(v_mat ->> 'item_code', '')), '');
      v_mat_variation := nullif(trim(coalesce(v_mat ->> 'variation_id', '')), '');
      if v_mat_variation is null and v_mat_code is not null then
        select nullif(trim(i."VariationId"), '') into v_mat_variation
        from public."Items" i where i."Code" = v_mat_code or i."VariationId" = v_mat_code
        order by (i."Code" = v_mat_code) desc limit 1;
      end if;
      if v_mat_code is null and v_mat_variation is not null then
        select nullif(trim(i."Code"), '') into v_mat_code
        from public."Items" i where i."VariationId" = v_mat_variation limit 1;
      end if;
      v_mat_name := coalesce(nullif(trim(coalesce(v_mat ->> 'name', '')), ''), v_mat_code, v_mat_variation);

      if v_mat_variation is null then
        raise exception 'Component "%" is not linked to a Pancake product (no VariationId in Items) - fix the item or remove it from the set.',
          coalesce(v_mat_name, '?');
      end if;

      v_next_ord := v_next_ord + 1;
      v_material_count := v_material_count + 1;
      insert into _set_explode_items (ord, line_id, variation_id, item_code, name, detail, quantity, price, note,
                                      discount, is_bonus, is_discount_percent, is_wholesale, set_idx)
      values (v_next_ord, null, v_mat_variation, v_mat_code, v_mat_name, v_mat_name, v_mat_qty, 0, v_material_note,
              '0'::jsonb, 'false'::jsonb, 'false'::jsonb, 'false'::jsonb, v_set_idx);
    end loop;

    -- "SET Materials: <name> x <qty>; ..." on the SET line, replacing any earlier one, keeping the rest.
    select string_agg(g.name || ' x ' || to_char(g.qty, 'FM999,999,990'), '; ' order by g.first_ord) into v_summary
    from (
      select name, sum(quantity) as qty, min(ord) as first_ord
      from _set_explode_items
      where set_idx = v_set_idx
      group by name
    ) g;

    select string_agg(l, E'\n') into v_kept_note
    from regexp_split_to_table(coalesce(v_parent.note, ''), E'\r?\n') l
    where trim(l) <> '' and ltrim(l) not ilike 'SET Materials:%';

    if v_summary is not null then
      v_kept_note := concat_ws(E'\n', v_kept_note, 'SET Materials: ' || v_summary);
    end if;

    update _set_explode_items set note = v_kept_note
    where ord = v_parent.ord;
  end loop;

  select jsonb_agg(jsonb_build_object(
    'line_id', line_id,
    'discount_each_product', discount,
    'is_bonus_product', is_bonus,
    'is_discount_percent', is_discount_percent,
    'is_wholesale', is_wholesale,
    'one_time_product', variation_id is null,
    'quantity', case when coalesce(abs(quantity), 0) = 0 then 1 else abs(quantity) end,
    'variation_id', variation_id,
    'note', nullif(note, ''),
    'variation_info', jsonb_build_object(
      'detail', coalesce(detail, name),
      'fields', null,
      'display_id', item_code,
      'name', coalesce(name, item_code, 'Online Item'),
      'product_display_id', item_code,
      'retail_price', coalesce(price, 0),
      'weight', 100
    )
  ) order by ord)
  into v_items
  from _set_explode_items
  where not removed;

  v_body := jsonb_build_object('items', v_items);

  v_patch_response := extensions.http((
    'PATCH', v_url,
    array[extensions.http_header('Accept', 'application/json'), extensions.http_header('Expect', '')],
    'application/json', v_body::text
  )::extensions.http_request);

  if v_patch_response.status = 404 or v_patch_response.status = 405 then
    v_put_response := extensions.http((
      'PUT', v_url,
      array[extensions.http_header('Accept', 'application/json'), extensions.http_header('Expect', '')],
      'application/json', v_body::text
    )::extensions.http_request);
    if v_put_response.status < 200 or v_put_response.status >= 300 then
      raise exception 'Pancake rejected the items update (PATCH %: % / PUT %: %)',
        v_patch_response.status, left(v_patch_response.content, 300),
        v_put_response.status, left(v_put_response.content, 300);
    end if;
  elsif v_patch_response.status < 200 or v_patch_response.status >= 300 then
    raise exception 'Pancake rejected the items update (HTTP %): %', v_patch_response.status, left(v_patch_response.content, 300);
  end if;

  -- Pancake wipes bank_payments on any PATCH unless re-sent (same as the POS and the other PATCHes).
  if v_bank_payments is not null then
    begin
      perform extensions.http((
        'PATCH', v_url,
        array[extensions.http_header('Accept', 'application/json'), extensions.http_header('Expect', '')],
        'application/json', jsonb_build_object('bank_payments', v_bank_payments)::text
      )::extensions.http_request);
    exception when others then
      null;
    end;
  end if;

  -- Pull the order back so OnlineOrderLines has Pancake's own line IDs for the new components.
  begin
    perform public._sync_online_order_detail(trim(p_order_id));
  exception when others then
    v_resynced := false;
  end;

  return jsonb_build_object('material_lines', v_material_count, 'resynced', v_resynced);
end;
$$;

grant execute on function public.staff_save_online_order_set_materials(text, text, text, jsonb) to anon;

-- ---------------------------------------------------------------------------
-- 6. Add-ons in the SET dialog (per "in the local pos its asking for medias" - "can you add it on the
--    package set in the portal?"): the POS's accessory slots (MainForm.cs PromptForAquariumSetAccessory-
--    Selection - Media 1-5, Light, Mesh Bag, Pump, Pipe) let staff add items that are NOT in the package.
--    Same item pool as the POS's LoadAquariumAccessoryItemChoices: active Items whose category is one of
--    the slot's categories, or whose code / name / description contains the slot's keyword. Returned per
--    Pancake variant (an item without variants only if it has its own VariationId - the save refuses
--    anything not linked to Pancake). p_query narrows by code / name / description / SKU. Max 60 rows.
create or replace function public.staff_search_set_accessory_items(
  p_admin_username text,
  p_admin_password text,
  p_kind text,
  p_query text default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_cats text[];
  v_keyword text;
  v_query text := nullif(trim(coalesce(p_query, '')), '');
  v_result jsonb;
begin
  if not public.is_staff_authorized(p_admin_username, p_admin_password) then
    raise exception 'Not authorized.';
  end if;

  case lower(coalesce(p_kind, ''))
    when 'media' then
      v_cats := array['MEDIA', 'MEDIAS', 'FILTERMEDIA', 'FILTER MEDIA', 'FILTERMEDIAS', 'FILTER MEDIAS']; v_keyword := 'MEDIA';
    when 'light' then
      v_cats := array['LIGHT', 'LIGHTS']; v_keyword := 'LIGHT';
    when 'meshbag' then
      v_cats := array['MESH', 'MESH BAG', 'MESHBAG', 'BAG']; v_keyword := 'MESH';
    when 'pump' then
      v_cats := array['PUMP', 'PUMPS']; v_keyword := 'PUMP';
    when 'pipe' then
      v_cats := array['PIPE', 'PIPES', 'PVC']; v_keyword := 'PIPE';
    else
      raise exception 'Unknown add-on type "%".', coalesce(p_kind, '');
  end case;

  with pool as (
    select i.* from public."Items" i
    where coalesce(i."IsActive", true)
      and (upper(trim(coalesce(i."CategoryCode", ''))) = any(v_cats)
           or i."Code" ilike '%' || v_keyword || '%'
           or coalesce(i."Name", '') ilike '%' || v_keyword || '%'
           or coalesce(i."Description", '') ilike '%' || v_keyword || '%')
  ),
  candidates as (
    select v."VariationId"::text as variation_id,
           coalesce(nullif(trim(v."ItemCode"), ''), v."MainItemCode")::text as item_code,
           coalesce(nullif(trim(v."VariantName"), ''), nullif(trim(p."Name"), ''), p."Code")::text as name,
           coalesce(nullif(trim(p."Description"), ''), nullif(trim(p."Name"), ''), '')::text as description,
           coalesce(nullif(trim(v."VariantName"), ''), '')::text as variant_name,
           coalesce(nullif(trim(v."SKU"), ''), nullif(trim(p."SKU"), ''), '')::text as sku,
           coalesce(v."Price", p."Price", 0) as price
    from pool p
    join public."Variants" v on v."MainItemCode" = p."Code" or v."ItemCode" = p."Code"
    union all
    select p."VariationId"::text, p."Code"::text,
           coalesce(nullif(trim(p."Name"), ''), p."Code")::text,
           coalesce(nullif(trim(p."Description"), ''), nullif(trim(p."Name"), ''), '')::text,
           ''::text,
           coalesce(nullif(trim(p."SKU"), ''), '')::text,
           coalesce(p."Price", 0)
    from pool p
    where nullif(trim(p."VariationId"), '') is not null
      and not exists (select 1 from public."Variants" v where v."MainItemCode" = p."Code" or v."ItemCode" = p."Code")
  ),
  picked as (
    select distinct on (c.variation_id) c.*
    from candidates c
    where nullif(trim(c.variation_id), '') is not null
      and (v_query is null
           or (c.item_code || ' ' || c.name || ' ' || c.description || ' ' || c.sku) ilike '%' || v_query || '%')
    order by c.variation_id
  )
  select coalesce(jsonb_agg(to_jsonb(r) order by r.description, r.name, r.sku), '[]'::jsonb) into v_result
  from (select * from picked order by description, name, sku limit 60) r;

  return v_result;
end;
$$;

grant execute on function public.staff_search_set_accessory_items(text, text, text, text) to anon;
